name: tape_letape
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Utils
  logger: ^1.1.0
  equatable: ^2.0.3
  hexcolor: ^2.0.7
  uuid: 3.0.6


  #Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0

  #BLoC
  flutter_bloc: ^8.0.1

  #DI
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true