name: tape_letape
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Utils
  logger: ^1.1.0


  #Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true